implement Mow algorithm
ESoufiane/mowItNow pull request #1
Opened 2024-08-04 12:23 UTC by ESoufiane

2024-08-10 09:36 UTC, walidbensmida requested changes

2024-08-10 09:36 UTC, walidbensmida commented on src/main/java/org/mowItNow/domain/model/MoveType.java
> +public enum MoveType {
```suggestion
public enum MoveDirection{
```

2024-08-10 09:36 UTC, walidbensmida commented on src/main/java/org/mowItNow/domain/model/Direction.java
> +public enum Direction {
```suggestion
public enum Orientation{
```

2024-08-10 09:36 UTC, walidbensmida commented on src/main/java/org/mowItNow/infra/adapter/InputFileReader.java
> +    public static LawnLimit mapToLawnLimit(List<String> lines) {
Delete static and use normal methods with object instantation

2024-08-10 09:36 UTC, walidbensmida commented on src/main/java/org/mowItNow/infra/adapter/InputFileReader.java
> +public class InputFileReader {
```suggestion
public class InstructionFileReader{
```

2024-08-10 09:36 UTC, walidbensmida commented on src/main/java/org/mowItNow/infra/adapter/InputFileReader.java
> +            throw new IllegalArgumentException("file lines are not valid " + lines);
Manage with custom exceptions

2024-08-10 09:36 UTC, walidbensmida commented on src/main/java/org/mowItNow/infra/adapter/InputFileReader.java
> +    public static List<Mower> mapToMowers(List<String> lines) {
Take inspiration from this code 
public static List<Mower> parseMowersFromLines(List<String> fileLines) {
    var mowers = new ArrayList<Mower>();  // Clear and reduces redundancy

    if (fileLines.size() % 2 != 1) {
        throw new MowerParsingException(INVALID_INPUT_ERROR + fileLines);
    }

    for (int i = 1; i < fileLines.size(); i += 2) {
        String[] positionComponents = fileLines.get(i).split(" "); // String[] is clearer here

        if (positionComponents.length != 3) {
            throw new MowerParsingException(INVALID_MOWER_DATA_ERROR + (i + 1) + ", but found: " + fileLines.get(i));
        }

        var position = new Position(  // Clear type inference
            Integer.parseInt(positionComponents[0]), 
            Integer.parseInt(positionComponents[1]), 
            Direction.valueOf(positionComponents[2])
        );

        var moveTypes = MoveType.parseMoveTypes(fileLines.get(i + 1));  // Clear and concise

        mowers.add(new Mower(position, moveTypes));
    }

    return mowers;
}

2024-08-10 09:36 UTC, walidbensmida commented on src/main/java/org/mowItNow/infra/adapter/InputFileReader.java
> +public class InputFileReader {
Reader is not the correct name, because the class is parsing the file, you should respect the single responsability principle

2024-08-11 16:12 UTC, ESoufiane commented on src/main/java/org/mowItNow/domain/spi/MowerSpi.java
> +    List<Mower> getAllMowers();
SPI for Service Provider Interface. It's used as a port in Hexagonal Architecture to define interactions with external services

2024-08-12 08:41 UTC, closed without merging